# Skill name
op-office-locations

# Description
Generate an IMI-branded office map for an Official Partner. Use when given a partner name to create a fully auto-updating map that reads office addresses from Airtable and deploys via Netlify. Outputs a fetch-offices.js file ready to be uploaded to GitHub.

# Instructions
When asked to create an office map for a partner, generate a fetch-offices.js file with the following exact specifications:

## Map style
- Grey land fill: #ededed
- Grey borders: #cccccc, weight 0.5
- White/transparent ocean background
- No attribution, no zoom controls, no panning, no dragging — completely static map
- HQ pin: red diamond (#c71e1d), size 20
- Office pins: blue diamond (#1d81a2), size 13
- Pins are rotated squares (SVG rect rotated 45 degrees)
- Label above map: "Headquarters' location in red" in Roboto Condensed, 12px, grey (#888)
- Popups show: HQ label (if applicable), city name in uppercase, full address
- Map auto-fits bounds to all office locations with 60px padding, maxZoom 8
- Antarctica is filtered out from the GeoJSON
- World GeoJSON loaded from: https://raw.githubusercontent.com/holtzy/D3-graph-gallery/master/DATA/world.geojson
- Fonts: Roboto Condensed (city names), Libre Baskerville (addresses)

## Airtable connection
- Reads from field: "Office Locations" OR "Office Location(s)" (tries both)
- Addresses are one per line, split by newline
- HQ address starts with "HQ " prefix
- Geocoding: extracts last 2 comma-separated parts of address (City, Country) and sends to Nominatim API
- Nominatim rate limit: 1.1 second delay between requests
- User-Agent header: "IMI-OfficeMaps/1.0"
- Partner is found by matching "Name" field containing the partner name (case insensitive)

## Environment variables required
- AIRTABLE_API_KEY
- AIRTABLE_BASE_ID (always: appq67wE0uXz3e1IC)
- AIRTABLE_TABLE_ID (always: tbliXV6iJMkbWyqf2)

## Output
- Script writes a complete self-contained index.html with all offices baked in
- index.html has no external dependencies except Leaflet CDN and Google Fonts
- No offices.json file — everything goes directly into index.html

## Deployment
- Netlify runs fetch-offices.js as build command
- netlify.toml: build command = "node fetch-offices.js", publish = "."
- Daily auto-update via Netlify scheduled deploy or manual trigger
- WordPress embed: <iframe src="[netlify-url]" width="100%" height="420" frameborder="0" style="border:none;"></iframe>

## GitHub repo structure
- fetch-offices.js (the build script)
- index.html (generated by script, do not edit manually)
- netlify.toml (Netlify build config)
- README.md (optional)
- .github/workflows/deploy.yml (legacy, ignore — not used)

## Notes
- Each partner gets their own GitHub repo and Netlify project
- All partners share the same Airtable base and table
- Only the partner name changes between maps
- Airtable token name: imi-op-office-map
